info:
  app:
    name: Composite PK sample
    description: A hibernate composite PK sample
    version: 1.0.0

spring:
  datasource:
    initialization-mode: always
    url: jdbc:h2:mem:sampledb;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update
